# Generated by Django 4.2.11 on 2024-09-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findJobs', '0003_job_country_jobuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
