# Generated by Django 4.2.11 on 2024-09-28 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('findJobs', '0005_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='selected_by',
            field=models.ManyToManyField(blank=True, related_name='selected_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
